
docker run -d --name sonarqube -p 9000:9000 sonarqube:10.7-community
sonar.projectKey=jest-sonarcube
sonar.projectName=jest-sonarcube
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=src
sonar.inclusions=src/**/*.ts,src/**/*.tsx
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/setupTests.ts,src/main.tsx,node_modules/**,dist/**,coverage/**
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.host.url=https://potential-chainsaw-wr6jgw4vp75g2gg67-9000.app.github.dev
# Pass token via env: 
SONAR_TOKEN=sqp_ee87cdd3e2a0ed6ee8a865de2cb22054c905e5f1

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
